secrets: secrets.yml

templates:
  download:
    seen: local
    verify_ssl_certificates: no
    priority: 2
    transmission:
      host: localhost
      port: 9091
      username: '{{ secrets.transmission.user }}'
      password: '{{ secrets.transmission.password }}'
      addpaused: no

tasks:
  # download las peliculas de imdb
  movie-queue:
    trakt_list:
      username: '{{secrets.trakt.user}}'
      account: '{{secrets.trakt.user}}'
      list: watchlist
      type: movies
    accept_all: yes
    trakt_remove:
      username: '{{secrets.trakt.user}}'
      account: '{{secrets.trakt.user}}'
      list: watchlist
    movie_queue:
      action: add
      quality: hdrip+ !cam
    seen: local
  #get the movies from IMDB
  get_imdb:
    verify_ssl_certificates: no
    imdb:
      min_score: 6.2
      min_votes: 2000
      min_year: 1985
    rss:
      url: http://kickass.to/movies/?rss=1
    accept_all: yes
    movie_queue:
      action: add
      quality: hdrip+ !cam
    seen: local

  # download shows from torrent rss feeds
  download-shows:
    template: [download]
    ### Main RSS feed to keep up
    rss: http://showrss.info/rss.php?user_id={{ secrets.showrss.user_id }}&hd=null&proper=null
    accept_all: yes
    exists_series:
      - /media/transmission/downloading
      - /media/transmission/series_flex
      - /media/transmission/others
      - /media/films/shows/{{series_name}}
    priority: 2
    transmission:
      path: /media/transmission/series_flex

 #download movies from queue, from rss feed
  download-movies:
    template: [download]
    discover:
      what:
        - emit_movie_queue: yes
      from:
        - torrentz: verified
        - kat:
            category: movies
            verified: yes
        - piratebay:
            category: movies
        - rarbg:
            sorted_by: seeders

    movie_queue: accept
    exists_movie:
      path:
        - /media/transmission/series_films
        - /media/films/films
      allow_different_qualities: better
#      [lookup]: {imdb|no}
#    seen: local
    regexp:
      reject:
        - \b3D\b: {from: title}
#    priority: 2
    transmission:
      path: /media/transmission/films_flex

# sorting task
  sort-shows:
    filesystem:
      # directory with the files to be sorted
      path: /media/transmission/series_flex
      recursive: yes
      # fetch all avi, mkv and mp4 files, skips the .part files (unfinished torrents)
      regexp: '.*\.(avi|mkv|mp4)$'
    regexp:
      reject:
        - \bsample\b: {from: title}
    # this is needed for the episode names
    thetvdb_lookup: yes
    require_field: [series_name, series_id]
    all_series:
      # for some reason all_series rejects all episodes here, even with seen: local, so parse_only must be added
      parse_only: yes
    # TVDB doesn't recognise "Adventure Time with Finn and Jake" so you must add such exceptions here manually
    series:
      settings:
        numeric:
          ep_regexp:
            - (\d\d)(\d\d)
            - (\d)(\d\d)
          parse_only: yes
        sequence:
          identified_by: sequence
      numeric:
        - Supernatural
        - The Big Bang Theory
    accept_all: yes
    no_entries_ok: yes
    seen: local
    copy:
      # this is where the series will be put
      to: /media/films/shows/{{ series_name }}/Season {{series_season}}
      # save the file as "Series Name - SxxEyy - Episode Name.ext"
      filename: '{{ series_name }} - {{ series_id }} - {{ tvdb_ep_name }}{{ location | pathext }}'
      along:
        - srt
        - en.srt
        - es.srt
        - nfo

  # SORT DOWNLOADED MOVIES
  sort-movies:
    filesystem:
      path: /media/transmission/films_flex
      recursive: yes
      # fetch all avi, mkv and mp4 files, skips the .part files (unfinished torrents)
      regexp: '.*\.(avi|mkv|mp4)$'
    accept_all: yes
    no_entries_ok: yes
    imdb_lookup: yes
    tmdb_lookup: yes
    seen: local
    priority: 4
    regexp:
      reject:
        - \bsample\b: {from: title}
        - \RARBG\b: {from: title}
    require_field: [movie_name, movie_year]
    copy:
      to: /media/films/films/{{ movie_name }} ({{ movie_year }})
      filename: '{{ movie_name }} ({{ movie_year }}) - {{ quality }}.{{ location[-3:] }}'

  subtitles:
      filesystem:
        path:
          - /media/transmission/series_flex
          - /media/transmission/films_flex
        regexp: '.*\.(avi|mkv|mp4)$'
        recursive: yes
      regexp:
        reject:
          - \bsample\b: {from: title}
      accept_all: yes
      no_entries_ok: yes
      seen: local
      #disable: [retry_failed]
      subliminal:
        languages:
          - eng
          - spa
        exact_match: yes
      priority: 3


#  clean-transmission:
#    manual: yes
#    disable: [details]
#    clean_transmission:
#      host: localhost
#      port: 9091
#      username: '{{ secrets.transmission.user }}'
#      password: '{{ secrets.transmission.password }}'
#      finished_for: 7 days
#      min_ratio: 0.85
#      delete_files: yes
#      transmission_seed_limits: yes

    
schedules:
  - tasks: 
      - movie-queue
      - get_imdb
      - download-shows
      - download-movies
      - sort-movies
      - sort-shows
      - subtitles

    interval:
      hours: 2
